<?xml version="1.0" encoding="utf-8"?><Database Name="dbEtrevistas" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-GKJHEGU\MATITEST;Initial Catalog=dbEtrevistas;Integrated Security=True" SettingsObjectName="Sabre.Entities.Properties.Settings" SettingsPropertyName="dbEtrevistasConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EntrevistaSet" Member="EntrevistaSets">
    <Type Name="EntrevistaSet">
      <Column Name="EntrevistaId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DNI" Type="System.String" DbType="NVarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="Asiste" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Valoracion" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>