//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryInfraestructure.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrevista
    {
        public int EntrevistaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string DNI { get; set; }
        public short Asiste { get; set; }
        public short Valoracion { get; set; }
    }
}
